const {_electron}=require('@playwright/test');const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'..'),out=path.resolve(root,'../../work');fs.mkdirSync(out,{recursive:true});
(async()=>{
 const profile=fs.mkdtempSync(path.join(out,'creatures-profile-')),app=await _electron.launch({executablePath:path.join(root,'node_modules/electron/dist/Electron.app/Contents/MacOS/Electron'),args:[root,`--user-data-dir=${profile}`],env:{...process.env,VITE_DEV_SERVER_URL:'http://127.0.0.1:5188/'}});
 try{
 const page=await app.firstWindow(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.waitForSelector('.pond-canvas');
 await page.evaluate(()=>{const c=document.createElement('canvas');c.width=512;c.height=192;const x=c.getContext('2d');x.fillStyle='#fff6df';x.beginPath();x.ellipse(275,96,148,52,0,0,Math.PI*2);x.fill();x.fillStyle='#e85e3b';x.beginPath();x.ellipse(355,76,29,29,0,0,Math.PI*2);x.fill();localStorage.setItem('fusheng-fish',JSON.stringify([{id:'legacy-test',name:'旧画稿',texture:c.toDataURL()}]));localStorage.setItem('fusheng-settings',JSON.stringify({season:'autumn',weather:'sunny',day:'day',fishCount:12,fishSize:1,turtleCount:0,quality:'high',sound:false,volume:.18}))});await page.reload();
 async function captureEngine(){await page.evaluate(async()=>{const url=performance.getEntriesByType('resource').map(r=>r.name).findLast(u=>u.includes('/src/engine/pond.js'));const {PondEngine}=await import(url||'/src/engine/pond.js');const render=PondEngine.prototype.render;PondEngine.prototype.render=function(...args){window.testEngine=this;return render.apply(this,args)}});await page.waitForFunction(()=>window.testEngine)}await captureEngine();
 await page.waitForFunction(()=>[...window.testEngine.images.values()].every(i=>i.skin));
 await page.getByRole('button',{name:'画锦鲤',exact:true}).click();await page.getByRole('slider',{name:'新锦鲤大小'}).press('End');
 const board=page.getByLabel('锦鲤绘画画布'),box=await board.boundingBox();await page.waitForTimeout(150);
 await page.waitForFunction(()=>{const c=document.querySelector('[aria-label="锦鲤绘画画布"]');return c&&c.getContext('2d').getImageData(800,300,1,1).data[3]>0});const before=await board.evaluate(c=>c.toDataURL());await page.getByRole('button',{name:'颜色 #203b38',exact:true}).click();
 async function paint(){await page.mouse.move(box.x+box.width*.60,box.y+box.height*.46);await page.mouse.down();await page.mouse.move(box.x+box.width*.67,box.y+box.height*.53,{steps:10});await page.mouse.up();await page.waitForTimeout(100)}
 await paint();const painted=await board.evaluate(c=>c.toDataURL());assert.ok(painted!==before,'draw changes anatomy preview');
 await page.getByRole('button',{name:'撤销一笔',exact:true}).click();await page.waitForTimeout(100);assert.ok(await board.evaluate(c=>c.toDataURL())===before,'undo restores paint');await paint();
 const draft=await board.evaluate(c=>c.toDataURL());await page.getByRole('button',{name:/我的锦鲤/}).click();await page.getByRole('button',{name:'绘制锦鲤',exact:true}).click();await page.waitForTimeout(100);assert.ok(await board.evaluate(c=>c.toDataURL())===draft,'tab change preserves draft');
 await page.getByRole('textbox',{name:'锦鲤名字'}).fill('墨游测试');await page.screenshot({path:path.join(out,'koi-studio-1.4.png')});await page.getByRole('button',{name:'放入池塘',exact:true}).click();
 await page.waitForFunction(()=>window.testEngine.sim.fish.some(f=>f.custom?.name==='墨游测试'));let custom=await page.evaluate(()=>{const f=window.testEngine.sim.fish.find(f=>f.custom?.name==='墨游测试');window.savedFishIdentity=f;return{size:f.custom.size,length:f.length,appearance:f.custom.appearance}});assert.equal(custom.size,1.8);assert.equal(custom.appearance,'skin-v2');assert.ok(Math.abs(custom.length-136.8)<.001);
 await page.getByRole('button',{name:'画锦鲤',exact:true}).click();await page.getByRole('button',{name:/我的锦鲤/}).click();await page.getByRole('slider',{name:'墨游测试的大小'}).press('Home');await page.waitForFunction(()=>window.savedFishIdentity.custom.size===.55);assert.ok(await page.evaluate(()=>window.testEngine.sim.fish.includes(window.savedFishIdentity)));
 await page.screenshot({path:path.join(out,'koi-collection-1.4.png')});await page.getByRole('button',{name:/小乌龟/}).click();await page.getByRole('button',{name:'请一只入池',exact:true}).click();
 for(let i=0;i<3;i++)await page.getByRole('button',{name:'增加一只小乌龟',exact:true}).click();assert.equal(await page.getByRole('button',{name:'增加一只小乌龟',exact:true}).isDisabled(),true);await page.waitForFunction(()=>window.testEngine.sim.turtles.length===4);await page.screenshot({path:path.join(out,'turtle-studio-1.4.png')});
 await page.getByRole('button',{name:'关闭面板',exact:true}).click();await page.getByRole('button',{name:'设置',exact:true}).click();await page.getByRole('slider',{name:'锦鲤整体大小'}).press('End');await page.waitForFunction(()=>window.testEngine.options.fishSize===1.6);
 await page.getByRole('button',{name:/暂停片刻/}).click();const frozen=await page.evaluate(()=>JSON.stringify({fish:window.testEngine.sim.fish,turtles:window.testEngine.sim.turtles}));await page.waitForTimeout(300);assert.equal(await page.evaluate(()=>JSON.stringify({fish:window.testEngine.sim.fish,turtles:window.testEngine.sim.turtles})),frozen);await page.getByRole('button',{name:/继续游动/}).click();await page.getByRole('button',{name:'关闭面板',exact:true}).click();
 await page.reload();await captureEngine();await page.waitForFunction(()=>window.testEngine.sim.turtles.length===4&&window.testEngine.options.fishSize===1.6);
 const saved=await page.evaluate(()=>{const a=window.testEngine.sim.fish.find(f=>f.custom?.name==='墨游测试'),b=window.testEngine.sim.fish.find(f=>f.custom?.id==='legacy-test');return{size:a.custom.size,length:a.length,legacyAppearance:b.custom.appearance,turtles:window.testEngine.sim.turtles.length}});assert.equal(saved.size,.55);assert.ok(Math.abs(saved.length-66.88)<.01);assert.equal(saved.legacyAppearance,'legacy');
 const p=await page.evaluate(()=>window.testEngine.sim.turtles.map(t=>[t.x,t.y]));await page.waitForTimeout(1000);assert.notDeepEqual(await page.evaluate(()=>window.testEngine.sim.turtles.map(t=>[t.x,t.y])),p);await page.screenshot({path:path.join(out,'creatures-pond-1.4.png')});
 const cdp=await page.context().newCDPSession(page);await cdp.send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:2,mobile:true});await page.getByRole('button',{name:'画锦鲤',exact:true}).click();await page.getByRole('slider',{name:'新锦鲤大小'}).press('End');await page.screenshot({path:path.join(out,'koi-studio-mobile-1.4.png')});assert.ok(await page.getByRole('button',{name:'放入池塘',exact:true}).isVisible());await page.getByRole('button',{name:'关闭面板',exact:true}).click();await cdp.send('Emulation.clearDeviceMetricsOverride');
 // Maximum population, mixed painted koi sizes, storm, 4 turtles: real desktop GPU load.
 await page.evaluate(()=>{const pattern=JSON.parse(localStorage.getItem('fusheng-fish')).find(f=>f.appearance==='skin-v2');localStorage.setItem('fusheng-fish',JSON.stringify(Array.from({length:12},(_,i)=>({...pattern,id:'load-'+i,size:.6+i*.1}))));localStorage.setItem('fusheng-settings',JSON.stringify({...JSON.parse(localStorage.getItem('fusheng-settings')),fishCount:24,turtleCount:4,fishSize:1.6,season:'autumn',weather:'stormy',quality:'high'}))});await page.reload();await captureEngine();await page.waitForFunction(()=>window.testEngine.sim.fish.length===36&&[...window.testEngine.images.values()].every(i=>i.skin));await page.evaluate(()=>window.pondDesktop.setDesktopMode(true));await page.waitForFunction(()=>window.testEngine.options.desktopMode);
 async function measure(name){await page.waitForTimeout(1000);const result=await page.evaluate(()=>new Promise(resolve=>{let start=0,previous=0;const times=[];function frame(t){if(!start)start=t;if(previous)times.push(t-previous);previous=t;if(t-start<5000)requestAnimationFrame(frame);else{times.sort((a,b)=>a-b);resolve({...window.testEngine.getStats(),rafFPS:times.length*1000/(t-start),p95:times[Math.floor(times.length*.95)],slow:times.filter(v=>v>33.5).length})}}requestAnimationFrame(frame)}));console.log(JSON.stringify({name,...result}));return{name,...result}}
 const performance=[await measure('4k-36-koi-4-turtles-storm')];for(const [name,width,height] of [['5k',2560,1440],['6k',3072,1728]]){await cdp.send('Emulation.setDeviceMetricsOverride',{width,height,deviceScaleFactor:2,mobile:false});await page.waitForFunction(w=>document.querySelector('.pond-canvas').width===w,width*2);performance.push(await measure(name+'-36-koi-4-turtles-storm'))}
 assert.ok(performance.every(p=>p.fishCount===36&&p.turtleCount===4&&p.fps>=50),'population and frame budget');assert.deepEqual(errors,[]);
 const result={result:'PASS',custom,saved,paintUndoAndTabPersistence:true,legacyUpgrade:true,turtleLimit:true,pause:true,mobile:true,performance,errors};fs.writeFileSync(path.join(out,'creatures-1.4.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result));
 }finally{await app.close();fs.rmSync(profile,{recursive:true,force:true})}
})().catch(e=>{console.error(e);process.exitCode=1});
