const {_electron}=require('@playwright/test');const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'..'),out=path.resolve(root,'../../work');fs.mkdirSync(out,{recursive:true});
(async()=>{const profile=fs.mkdtempSync(path.join(out,'environment-profile-')),app=await _electron.launch({executablePath:path.join(root,'node_modules/electron/dist/Electron.app/Contents/MacOS/Electron'),args:[root,`--user-data-dir=${profile}`],env:{...process.env,VITE_DEV_SERVER_URL:'http://127.0.0.1:5188/'}});
try{const page=await app.firstWindow(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.waitForSelector('.pond-canvas');
let staleAssetRequests=0;await page.route('**/assets/autumn.png*',route=>{if(!new URL(route.request().url()).search){staleAssetRequests++;return route.abort()}return route.continue()});
await page.evaluate(()=>{localStorage.setItem('fusheng-settings',JSON.stringify({season:'autumn',weather:'sunny',day:'day',fishCount:24,turtleCount:4,fishSize:1.3,quality:'high',sound:false,volume:.2}));const c=document.createElement('canvas');c.width=512;c.height=128;const x=c.getContext('2d');x.fillStyle='#fff6df';x.fillRect(0,0,512,128);x.fillStyle='#e76c44';x.fillRect(125,20,80,80);x.fillRect(380,0,50,90);localStorage.setItem('fusheng-fish',JSON.stringify(Array.from({length:12},(_,i)=>({id:'test-'+i,name:'测试锦鲤',texture:c.toDataURL(),size:.6+i*.1,appearance:'skin-v2'}))))});await page.reload();
await page.evaluate(async()=>{const url=performance.getEntriesByType('resource').map(r=>r.name).findLast(u=>u.includes('/src/engine/pond.js'));const {PondEngine}=await import(url);const render=PondEngine.prototype.render;PondEngine.prototype.render=function(...args){window.testEngine=this;return render.apply(this,args)}});await page.waitForFunction(()=>window.testEngine?.landscape.season==='autumn'&&window.testEngine.sim.fish.length===36&&[...window.testEngine.images.values()].every(i=>i.skin));
assert.equal(staleAssetRequests,0,'new art must bypass the pre-cleanup asset cache');
const motion=await page.evaluate(()=>{const e=window.testEngine,l=e.landscape,g=l.gl;e.updateOptions({paused:true});function sample(uv){const ratio=l.width/l.height,cx=Math.min(1,ratio/(16/9)),cy=Math.min(1,(16/9)/ratio),x=((uv[0]-.5)/cx+.5)*l.canvas.width,y=(1-((uv[1]-.5)/cy+.5))*l.canvas.height;const p=new Uint8Array(24*24*4);g.readPixels(Math.max(0,Math.round(x-12)),Math.max(0,Math.round(y-12)),24,24,g.RGBA,g.UNSIGNED_BYTE,p);return p}const spots={center:[.5,.46],leftShore:[.1,.3],rockShore:[.76,.72],dryRock:[.89,.85]};const metrics={};for(const [key,uv]of Object.entries(spots)){l.render(0,e.options,{});const a=sample(uv);l.render(4,e.options,{});const b=sample(uv);metrics[key]=a.reduce((s,v,i)=>s+Math.abs(v-b[i]),0)/a.length}l.render(0,{...e.options,reducedMotion:true},{});const a=sample(spots.center);l.render(4,{...e.options,reducedMotion:true},{});const b=sample(spots.center);metrics.reducedMotion=a.reduce((s,v,i)=>s+Math.abs(v-b[i]),0);e.updateOptions({paused:false});return metrics});
assert.ok(motion.center>1&&motion.leftShore>1&&motion.rockShore>1,'water and shore areas must move');assert.equal(motion.reducedMotion,0);assert.ok(motion.dryRock<.5,'dry boulder cores stay anchored');await page.screenshot({path:path.join(out,'environment-autumn-1.5.png')});
await page.getByRole('button',{name:'打开天气设置',exact:true}).click();await page.getByRole('button',{name:'雷雨',exact:true}).click();await page.getByRole('button',{name:'关闭面板',exact:true}).click();await page.waitForFunction(()=>window.testEngine.atmosphere.rainHits>40);
await page.evaluate(()=>window.pondDesktop.setDesktopMode(true));await page.waitForFunction(()=>window.testEngine.options.desktopMode);const cdp=await page.context().newCDPSession(page);
async function measure(name){await page.waitForTimeout(1000);const stats=await page.evaluate(()=>new Promise(resolve=>{let start=0,last=0;const intervals=[];function sample(t){if(!start)start=t;if(last)intervals.push(t-last);last=t;if(t-start<6000)requestAnimationFrame(sample);else{intervals.sort((a,b)=>a-b);resolve({...window.testEngine.getStats(),rafFPS:intervals.length*1000/(t-start),p95:intervals[Math.floor(intervals.length*.95)],slow:intervals.filter(x=>x>33.5).length})}}requestAnimationFrame(sample)}));console.log(JSON.stringify({name,...stats}));return{name,...stats}}
const performance=[await measure('4k')];for(const [name,w,h]of [['5k',2560,1440],['6k',3072,1728]]){await cdp.send('Emulation.setDeviceMetricsOverride',{width:w,height:h,deviceScaleFactor:2,mobile:false});await page.waitForFunction(w=>document.querySelector('.pond-canvas').width===w,w*2);performance.push(await measure(name))}assert.ok(performance.every(p=>p.fps>=50&&p.rafFPS>=50&&p.fishCount===36&&p.turtleCount===4));await page.evaluate(()=>window.pondDesktop.showControls());await cdp.send('Emulation.clearDeviceMetricsOverride');
await page.getByRole('button',{name:'四时',exact:true}).click();await page.getByRole('button',{name:/春/}).click();await page.getByRole('button',{name:'关闭面板',exact:true}).click();await page.waitForFunction(()=>window.testEngine.landscape.season==='spring');await page.screenshot({path:path.join(out,'environment-spring-1.5.png')});
await cdp.send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:2,mobile:true});await page.screenshot({path:path.join(out,'environment-mobile-1.5.png')});await cdp.send('Emulation.clearDeviceMetricsOverride');
assert.deepEqual(errors,[]);const result={result:'PASS',staleAssetRequests,motion,performance,errors};fs.writeFileSync(path.join(out,'environment-1.5.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result));
await page.evaluate(()=>{localStorage.setItem('fusheng-fish','[]');localStorage.setItem('fusheng-settings',JSON.stringify({season:'autumn',weather:'sunny',day:'day',fishCount:12,turtleCount:1,quality:'high',sound:false,volume:.2}))});await page.reload();await page.waitForSelector('.pond-canvas');await page.waitForTimeout(4500);await page.screenshot({path:path.join(out,'pond-preview-1.5.png')});
}finally{await app.close();fs.rmSync(profile,{recursive:true,force:true})}})().catch(e=>{console.error(e);process.exitCode=1});
