const {_electron}=require('@playwright/test');const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'..'),out=path.resolve(root,'../../work');fs.mkdirSync(out,{recursive:true});
(async()=>{const profile=fs.mkdtempSync(path.join(out,'environment-profile-')),app=await _electron.launch({executablePath:path.join(root,'node_modules/electron/dist/Electron.app/Contents/MacOS/Electron'),args:[root,`--user-data-dir=${profile}`],env:{...process.env,VITE_DEV_SERVER_URL:'http://127.0.0.1:5188/'}});
try{const page=await app.firstWindow(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.waitForSelector('.pond-canvas');
let staleAssetRequests=0;await page.route('**/assets/autumn.png*',route=>{if(!new URL(route.request().url()).search){staleAssetRequests++;return route.abort()}return route.continue()});
await page.evaluate(()=>{localStorage.setItem('fusheng-settings',JSON.stringify({season:'autumn',weather:'sunny',day:'day',fishCount:24,turtleCount:4,fishSize:1.3,quality:'high',sound:false,volume:.2}));const c=document.createElement('canvas');c.width=512;c.height=128;const x=c.getContext('2d');x.fillStyle='#fff6df';x.fillRect(0,0,512,128);x.fillStyle='#e76c44';x.fillRect(125,20,80,80);x.fillRect(380,0,50,90);localStorage.setItem('fusheng-fish',JSON.stringify(Array.from({length:12},(_,i)=>({id:'test-'+i,name:'测试锦鲤',texture:c.toDataURL(),size:.6+i*.1,appearance:'skin-v2'}))))});await page.reload();
await page.evaluate(async()=>{const url=performance.getEntriesByType('resource').map(r=>r.name).findLast(u=>u.includes('/src/engine/pond.js'));const {PondEngine}=await import(url);const render=PondEngine.prototype.render;PondEngine.prototype.render=function(...args){window.testEngine=this;return render.apply(this,args)}});await page.waitForFunction(()=>window.testEngine?.landscape.season==='autumn'&&window.testEngine.sim.fish.length===36&&[...window.testEngine.images.values()].every(i=>i.skin));
assert.equal(staleAssetRequests,0,'new art must bypass the pre-cleanup asset cache');
const motion=await page.evaluate(()=>{const e=window.testEngine,l=e.landscape,g=l.gl;e.updateOptions({paused:true});function sample(uv){const ratio=l.width/l.height,cx=Math.min(1,ratio/(16/9)),cy=Math.min(1,(16/9)/ratio),x=((uv[0]-.5)/cx+.5)*l.canvas.width,y=(1-((uv[1]-.5)/cy+.5))*l.canvas.height;const p=new Uint8Array(24*24*4);g.readPixels(Math.max(0,Math.round(x-12)),Math.max(0,Math.round(y-12)),24,24,g.RGBA,g.UNSIGNED_BYTE,p);return p}const spots={center:[.5,.46],leftWater:[.17,.3],rockShore:[.76,.72],dryRock:[.89,.85],reeds:[.13,.70],branches:[.87,.10]};const metrics={};for(const [key,uv]of Object.entries(spots)){l.render(0,e.options,{});const a=sample(uv);l.render(4,e.options,{});const b=sample(uv);metrics[key]=a.reduce((s,v,i)=>s+Math.abs(v-b[i]),0)/a.length}l.render(0,{...e.options,reducedMotion:true},{});const a=sample(spots.reeds);l.render(4,{...e.options,reducedMotion:true},{});const b=sample(spots.reeds);metrics.reducedMotion=a.reduce((s,v,i)=>s+Math.abs(v-b[i]),0);e.updateOptions({paused:false});return metrics});
console.log(JSON.stringify({motion}));assert.equal(motion.center,0,'the submerged pond bed must stay fixed');assert.equal(motion.leftWater,0,'water beside reeds must not inherit their sway');assert.equal(motion.rockShore,0);assert.equal(motion.dryRock,0,'dry boulders stay anchored');assert.ok(motion.reeds>.1&&motion.branches>.1,'only local leaves sway');assert.equal(motion.reducedMotion,0);await page.screenshot({path:path.join(out,'environment-autumn-1.7.png')});
const swimBefore=await page.evaluate(()=>{const e=window.testEngine;return e.sim.fish.map(f=>({velocity:f.velocity,amplitude:f.swimAmplitude,phase:f.phase,heading:f.heading,tail:e.bodyPoint(f,0).y}))});
await page.mouse.click(1100,160);await page.waitForTimeout(1800);
const swimAfter=await page.evaluate(()=>{const e=window.testEngine;return e.sim.fish.map(f=>({velocity:f.velocity,amplitude:f.swimAmplitude,phase:f.phase,heading:f.heading,tail:e.bodyPoint(f,0).y}))});
const average=(a,key)=>a.reduce((sum,f)=>sum+f[key],0)/a.length;
const swim={beforeSpeed:average(swimBefore,'velocity'),afterSpeed:average(swimAfter,'velocity'),beforeAmplitude:average(swimBefore,'amplitude'),afterAmplitude:average(swimAfter,'amplitude'),movingTails:swimAfter.filter((f,i)=>Math.abs(f.tail-swimBefore[i].tail)>.15).length};
console.log(JSON.stringify({swim}));assert.ok(swim.afterSpeed>swim.beforeSpeed*1.1&&swim.afterAmplitude>swim.beforeAmplitude*1.05&&swim.movingTails>25,'actual feeding must engage flexible bodies');await page.screenshot({path:path.join(out,'feeding-motion-1.7.png')});
// Observe the real rain renderer over time, including all outer cells.
await page.getByRole('button',{name:'打开天气设置',exact:true}).click();await page.getByRole('button',{name:'细雨',exact:true}).click();await page.getByRole('button',{name:'关闭面板',exact:true}).click();
const rainCoverage=await page.evaluate(async()=>{
 const url=performance.getEntriesByType('resource').map(r=>r.name).findLast(u=>u.includes('/src/engine/atmosphere.js'));const {rainPosition}=await import(url);
 const e=window.testEngine,cells=new Set();for(let i=0;i<120;i++){for(const d of e.atmosphere.drops){const p=rainPosition(d,e.width,e.height,e.options);if(p.x>=0&&p.x<e.width&&p.y>=0&&p.y<e.height)cells.add(`${Math.floor(p.x/e.width*4)},${Math.floor(p.y/e.height*4)}`)}await new Promise(r=>setTimeout(r,50))}return [...cells];
});assert.equal(rainCoverage.length,16);await page.screenshot({path:path.join(out,'environment-rain-1.7.png')});
const shore=await page.evaluate(async()=>{
 const url=performance.getEntriesByType('resource').map(r=>r.name).findLast(u=>u.includes('/src/engine/surface-waves.js'));const {drawShoreRipples}=await import(url);const e=window.testEngine;
 const canvas=document.createElement('canvas');canvas.width=e.width;canvas.height=e.height;const c=canvas.getContext('2d');
 drawShoreRipples(c,5,e.width,e.height,e.options,e.isWater);const a=c.getImageData(0,0,e.width,e.height).data;c.clearRect(0,0,e.width,e.height);drawShoreRipples(c,8,e.width,e.height,e.options,e.isWater);const b=c.getImageData(0,0,e.width,e.height).data;
 let pixels=0,changed=0,left=0,right=0;for(let i=3;i<a.length;i+=4){if(a[i]){pixels++;const x=(i-3)/4%e.width,y=Math.floor((i-3)/4/e.width);if(x<e.width*.22&&y<e.height*.26)left++;if(x>e.width*.65&&y>e.height*.55)right++}if(a[i]!==b[i])changed++}return{pixels,changed,left,right};
});console.log(JSON.stringify({shore,rainCoverage}));assert.ok(shore.left>10&&shore.right>10&&shore.changed>100,'independent waves must move along both banks');
await page.getByRole('button',{name:'设置',exact:true}).click();await page.getByText('治愈流水声',{exact:true}).click();
await page.waitForFunction(()=>{const a=document.querySelector('[data-ambient="rain"]');return !a.paused&&a.currentTime>.2&&a.volume>0});
const rainAudio=await page.evaluate(async()=>{const a=document.querySelector('[data-ambient="rain"]');const context=new OfflineAudioContext(2,1,48000),b=await context.decodeAudioData(await (await fetch(a.currentSrc)).arrayBuffer());let peak=0,power=0;for(let c=0;c<b.numberOfChannels;c++){const data=b.getChannelData(c);for(const x of data){peak=Math.max(peak,Math.abs(x));power+=x*x}}return{url:a.currentSrc,duration:b.duration,peak,rms:Math.sqrt(power/b.length/b.numberOfChannels),time:a.currentTime,volume:a.volume,loop:a.loop}});
assert.ok(rainAudio.url.endsWith('rain.wav?v=1.7')&&rainAudio.peak<.09&&rainAudio.rms<.008&&rainAudio.loop);assert.equal(rainAudio.duration,45);
await page.getByText('治愈流水声',{exact:true}).click();await page.waitForFunction(()=>[...document.querySelectorAll('audio')].every(a=>a.paused&&a.volume===0));await page.getByRole('button',{name:'关闭面板',exact:true}).click();
await page.getByRole('button',{name:'打开天气设置',exact:true}).click();await page.getByRole('button',{name:'雷雨',exact:true}).click();await page.getByRole('button',{name:'关闭面板',exact:true}).click();await page.waitForFunction(()=>window.testEngine.atmosphere.rainHits>40);
await page.evaluate(()=>window.pondDesktop.setDesktopMode(true));await page.waitForFunction(()=>window.testEngine.options.desktopMode);const cdp=await page.context().newCDPSession(page);
async function measure(name){await page.waitForTimeout(1000);const stats=await page.evaluate(()=>new Promise(resolve=>{let start=0,last=0;const intervals=[];function sample(t){if(!start)start=t;if(last)intervals.push(t-last);last=t;if(t-start<6000)requestAnimationFrame(sample);else{intervals.sort((a,b)=>a-b);resolve({...window.testEngine.getStats(),rafFPS:intervals.length*1000/(t-start),p95:intervals[Math.floor(intervals.length*.95)],slow:intervals.filter(x=>x>33.5).length})}}requestAnimationFrame(sample)}));console.log(JSON.stringify({name,...stats}));return{name,...stats}}
const performance=[await measure('4k')];assert.deepEqual(performance[0].backgroundSize,[performance[0].width,performance[0].height]);for(const [name,w,h]of [['5k',2560,1440],['6k',3072,1728]]){await cdp.send('Emulation.setDeviceMetricsOverride',{width:w,height:h,deviceScaleFactor:2,mobile:false});await page.waitForFunction(w=>document.querySelector('.pond-canvas').width===w,w*2);performance.push(await measure(name));assert.deepEqual(performance.at(-1).backgroundSize,[w*2,h*2],'the background must retain the same native pixels as the fish');await page.screenshot({path:path.join(out,`native-${name}-1.7.png`)})}assert.ok(performance.every(p=>p.fps>=50&&p.rafFPS>=50&&p.fishCount===36&&p.turtleCount===4));await page.evaluate(()=>window.pondDesktop.showControls());await cdp.send('Emulation.clearDeviceMetricsOverride');
await page.getByRole('button',{name:'四时',exact:true}).click();await page.getByRole('button',{name:/春/}).click();await page.getByRole('button',{name:'关闭面板',exact:true}).click();await page.waitForFunction(()=>window.testEngine.landscape.season==='spring');await page.screenshot({path:path.join(out,'environment-spring-1.7.png')});
await cdp.send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:2,mobile:true});await page.screenshot({path:path.join(out,'environment-mobile-1.7.png')});await cdp.send('Emulation.clearDeviceMetricsOverride');
assert.deepEqual(errors,[]);const result={result:'PASS',staleAssetRequests,motion,shore,rainCoverage,swim,rainAudio,performance,errors};fs.writeFileSync(path.join(out,'environment-1.7.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result));
await page.evaluate(()=>{localStorage.setItem('fusheng-fish','[]');localStorage.setItem('fusheng-settings',JSON.stringify({season:'autumn',weather:'sunny',day:'day',fishCount:12,turtleCount:1,quality:'high',sound:false,volume:.2}))});await page.reload();await page.waitForSelector('.pond-canvas');await page.waitForTimeout(4500);await page.screenshot({path:path.join(out,'pond-preview-1.7.png')});
}finally{await app.close();fs.rmSync(profile,{recursive:true,force:true})}})().catch(e=>{console.error(e);process.exitCode=1});
