const {_electron}=require('@playwright/test');const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'..'),out=path.resolve(root,'../../work');fs.mkdirSync(out,{recursive:true});
(async()=>{const profile=fs.mkdtempSync(path.join(out,'environment-profile-')),app=await _electron.launch({executablePath:path.join(root,'node_modules/electron/dist/Electron.app/Contents/MacOS/Electron'),args:[root,`--user-data-dir=${profile}`],env:{...process.env,VITE_DEV_SERVER_URL:'http://127.0.0.1:5188/'}});
try{const page=await app.firstWindow(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.waitForSelector('.pond-canvas');
const staleAssetRequests=0,motion={},performance=[];await page.evaluate(()=>{localStorage.setItem('fusheng-settings',JSON.stringify({season:'autumn',weather:'sunny',day:'day',fishCount:12,turtleCount:0,quality:'high',sound:false,volume:.2}))});await page.reload();
await page.evaluate(async()=>{const url=performance.getEntriesByType('resource').map(r=>r.name).findLast(u=>u.includes('/src/audio/ambient.js'));const {AmbientMixer}=await import(url);const configure=AmbientMixer.prototype.configure;AmbientMixer.prototype.configure=function(...args){window.testMixer=this;return configure.apply(this,args)}});
await page.getByRole('button',{name:'打开天气设置',exact:true}).click();await page.getByRole('button',{name:'晴天',exact:true}).click();await page.getByRole('button',{name:'关闭面板',exact:true}).click();await page.getByRole('button',{name:'设置',exact:true}).click();await page.getByText('治愈流水声',{exact:true}).click();await page.waitForFunction(()=>window.testMixer&&document.querySelector('[data-ambient="stream"]').currentTime>.2);
await page.waitForFunction(()=>document.querySelector('[data-ambient="wind"]').paused);assert.equal(await page.locator('[data-ambient="wind"]').evaluate(a=>a.loop),false);
// Timers run through Playwright's clock; real WAV playback remains Chromium media playback.
await page.getByRole('button',{name:/暂停片刻/}).click();await page.evaluate(()=>window.testMixer.stopWind());await page.waitForFunction(()=>window.testMixer.timer===0);await page.clock.install();await page.clock.pauseAt(new Date(await page.evaluate(()=>Date.now()+1000)));await page.evaluate(()=>{const m=window.testMixer;m.stopWind();m.random=()=>0;m.scheduleWind(true)});await page.clock.runFor(50000);console.log('wind: 50 seconds of quiet');assert.equal(await page.locator('[data-ambient="wind"]').evaluate(a=>a.paused&&a.volume===0),true);
await page.clock.runFor(11500);await page.waitForFunction(()=>!document.querySelector('[data-ambient="wind"]').paused&&document.querySelector('[data-ambient="wind"]').volume>0);console.log('wind: gust is audible');const gust=await page.locator('[data-ambient="wind"]').evaluate(a=>({volume:a.volume,currentTime:a.currentTime,loop:a.loop}));await page.clock.runFor(7000);console.log(await page.evaluate(()=>({windActive:window.testMixer.windActive,targets:window.testMixer.targets,wind:{paused:document.querySelector('[data-ambient=wind]').paused,volume:document.querySelector('[data-ambient=wind]').volume}})));assert.equal(await page.locator('[data-ambient="wind"]').evaluate(a=>a.paused&&a.volume===0),true);await page.clock.runFor(70000);console.log('wind: silence restored between gusts');assert.equal(await page.locator('[data-ambient="wind"]').evaluate(a=>a.paused),true);
if(!await page.getByText('治愈流水声',{exact:true}).isVisible())await page.getByRole('button',{name:'设置',exact:true}).click();await page.getByText('治愈流水声',{exact:true}).click();await page.clock.runFor(10000);assert.equal(await page.locator('audio').evaluateAll(all=>all.every(a=>a.paused&&a.volume===0)),true);assert.deepEqual(errors,[]);
const result={result:'PASS',staleAssetRequests,motion,performance,gust,quietWind:true,errors};fs.writeFileSync(path.join(out,'wind-playback-1.5.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result));
}finally{await app.close();fs.rmSync(profile,{recursive:true,force:true})}})().catch(e=>{console.error(e);process.exitCode=1});
