import {useState,useRef,useEffect} from 'react';
import {Sun,Cloud,CloudRain,CloudSnow,CloudFog,CloudLightning,LocateFixed,Search,RefreshCw,Check,MapPin} from 'lucide-react';
import {searchCities} from '../lib/environment.js';
import {Panel} from './Panel.jsx';
export const WEATHER={sunny:{name:'晴天',Icon:Sun},cloudy:{name:'多云',Icon:Cloud},rainy:{name:'细雨',Icon:CloudRain},snowy:{name:'落雪',Icon:CloudSnow},stormy:{name:'雷雨',Icon:CloudLightning},foggy:{name:'薄雾',Icon:CloudFog}};
export default function WeatherPanel({env,mode,onChange,onClose,notify}){
 const [query,setQuery]=useState(''),[results,setResults]=useState([]),[busy,setBusy]=useState(false),[locating,setLocating]=useState(false),[error,setError]=useState('');const req=useRef(null),geo=useRef(null);
 const stopGeo=()=>{if(geo.current!==null){navigator.geolocation?.clearWatch(geo.current);geo.current=null}};
 useEffect(()=>()=>{req.current?.abort();stopGeo()},[]);
 async function search(e){e.preventDefault();req.current?.abort();const ctrl=new AbortController();req.current=ctrl;setBusy(true);setError('');try{const list=await searchCities(query.trim(),{signal:ctrl.signal});if(!ctrl.signal.aborted){setResults(list);if(!list.length)setError('没有找到这个城市，试试英文或拼音。')}}catch(err){if(!ctrl.signal.aborted)setError('城市查询暂不可用，请稍后重试。')}finally{if(!ctrl.signal.aborted)setBusy(false)}}
 // 能问浏览器的就问浏览器（更准）；问不到就走 IP 定位。★ 局域网 http:// 是非安全上下文，
 // 那时 navigator.geolocation 必然被拒 —— 那不是"用户没给权限"，硬走它只会弹一句误导的话。
 function browserGeoUsable(){return !window.pondDesktop&&!!navigator.geolocation&&window.isSecureContext}
 async function locate(){if(locating||busy||env.locationBusy)return;setError('');
  if(!browserGeoUsable()){setLocating(true);const r=await env.locate({userInitiated:true});setLocating(false);if(r.ok)notify(`已按网络位置更新城市：${r.city.name}`);return}
  setLocating(true);geo.current=navigator.geolocation.watchPosition(p=>{stopGeo();setLocating(false);env.setCity({id:'located',name:'当前位置',latitude:p.coords.latitude,longitude:p.coords.longitude,source:'approximate',locatedAt:Date.now()});notify('已使用你的位置更新天气')},()=>{stopGeo();setLocating(false);setError('未取得定位权限，可搜索城市或改按网络定位。')},{timeout:10000,maximumAge:600000})}
 return <Panel title="把窗外，带进池塘" subtitle="天气每 15 分钟更新，也可以随心选一种心情。" onClose={onClose}><div className="weather-current"><div><MapPin size={16}/><strong>{env.city.name}</strong><span>{env.data?`${Math.round(env.data.temperature)}°`: '—°'}</span></div><button className="icon-button" aria-label="刷新天气" onClick={env.refresh} disabled={env.status==='loading'}><RefreshCw size={17} className={env.status==='loading'?'spin':''}/></button></div><p className="weather-source">{env.status==='live'?`已更新 · ${new Date(env.data.updatedAt).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})}`:env.status==='loading'?'正在读取实时天气…':env.status==='cached'?'网络暂不可用 · 显示上次天气':'天气暂不可用 · 池塘使用默认晴天'}</p>{env.locationStatus==='approximate'&&<p className="inline-note">城市来自网络大致位置，可搜索修正或点下方重新定位。</p>}{env.locationStatus==='fallback'&&<p className="inline-note">自动定位暂不可用，先以武汉为默认城市；可点下方重试或直接搜索。</p>}<form onSubmit={search} className="city-search"><Search size={17}/><input aria-label="搜索城市" placeholder="搜索城市，如武汉、杭州" value={query} onChange={e=>setQuery(e.target.value)}/><button type="submit" disabled={busy||query.trim().length<2}>查找</button></form>{error||env.locationError?<p role="status" className="inline-note">{error||env.locationError}</p>:null}{results.length>0&&<div className="city-results">{results.map((c,i)=><button key={c.id||i} onClick={()=>{env.setCity(c);setResults([]);setQuery('');notify(`天气城市已切换为${c.name}`)}}><span>{c.name}<small>{c.country}</small></span><MapPin size={15}/></button>)}</div>}<button className="text-button locate" onClick={locate} disabled={locating||busy||env.locationBusy}><LocateFixed size={15}/>{locating||env.locationBusy?'正在定位…':browserGeoUsable()?'使用我的位置':env.locationStatus==='approximate'?'重新定位':'按网络定位城市'}</button><div className="section-divider"/><button className={`auto-choice ${mode==='auto'?'selected':''}`} onClick={()=>onChange('auto')}><span><RefreshCw size={17}/>跟随真实天气</span>{mode==='auto'&&<Check size={17}/>}</button><div className="weather-choices">{Object.entries(WEATHER).filter(([key])=>key!=='foggy').map(([key,{name,Icon}])=><button aria-pressed={mode===key} key={key} className={mode===key?'selected':''} onClick={()=>onChange(key)}><Icon size={23}/><span>{name}</span></button>)}</div><p className="attribution">天气数据来自 <a href="https://open-meteo.com/" target="_blank" rel="noreferrer">Open-Meteo</a> · 城市搜索 GeoNames</p></Panel>
}
